nuxeo/nuxeo-python-client

- nuxeo/nuxeo.py
- tests/test_nuxeo.py
Only test the keys of the dict if the dict returned by the server is not empty.
Also updating the docstring of the function.
> NXPY-30: Adapt the test

- CHANGELOG.rst
- LICENSE.txt
- README.rst
- nuxeo/__init__.py
- setup.cfg
- setup.py
We can now launch tests using `python setup.py test`.
Also:
- A fix with the version lookup
> NXDRIVE-26: Fix and tweaks for setup.cfg

- CHANGELOG.rst
- examples/find_duplicates.py
- nuxeo/batchupload.py
- nuxeo/blob.py
- nuxeo/common.py
- nuxeo/compat.py
- nuxeo/exceptions.py
- nuxeo/nuxeo.py
- nuxeo/operation.py
- nuxeo/repository.py
- tests/conftest.py
- tests/test_batchupload.py
- tests/test_groups.py
- tests/test_nuxeo.py
- tests/test_operation.py
- tests/test_repository.py
- tests/test_users.py
- tests/test_workflows.py
Add nuxeo/compat.py to manage imports that depends on the python version, and helpers (get_bytes(), get_text(), get_error_message()).
- Add test_batchupload.py::test_mimetype()
- Add test_nuxeo.py::test_request_token()
> NXPY-9: Python 3 support

- CHANGELOG.rst
- nuxeo/operations.py
- tests/test_operation.py
To be able to use a custom cache on the Drive side, I needed to move the `ops` attribute outside `__init__()`.
> NXPY-58: Fix operations caching

- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/exceptions.py
If there is another exception in between the current exception in process and the exception logging, the logged exception will not be the good one. It just adds noise, because `logging.exception()` logs the latest exception .
> NXPY-58: Do not log the exception in Client._handle_error()

- CHANGELOG.rst
- nuxeo/operations.py
- setup.cfg
```python
operations.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working.
```
> NXPY-67: Fix Python 3.7 DeprecationWarning with ABCs

- nuxeo/models.py
- nuxeo/operations.py
- tests/test_operation.py
I have created this simple fix to support `context` in an Operation payload (as required by e.g. `FileManager.Import`). Following sample code works now as expected:
```
nx = get_nuxeo_client()
operation = nx.operations.new('FileManager.Import')
operation.params = {
'context': {
'currentDocument': "/default-domain/UserWorkspaces/Administrator"
}
}
operation.input_obj = blob
operation.execute()
```
> NXPY-74: Support Operation context

- CHANGELOG.rst
- examples/find_duplicates.py
- nuxeo/__init__.py
- nuxeo/auth.py
- nuxeo/client.py
- nuxeo/compat.py
- nuxeo/directories.py
- nuxeo/documents.py
- nuxeo/endpoint.py
- nuxeo/exceptions.py
- nuxeo/groups.py
- nuxeo/models.py
- nuxeo/operations.py
- nuxeo/tasks.py
- nuxeo/uploads.py
- nuxeo/users.py
- nuxeo/utils.py
- nuxeo/workflows.py
- setup.cfg
- tests/server.py
- tests/test_document.py
- tests/test_repository.py
- tox.ini
This is to prevent internal error due to the use of deprecated `pytest_namespace`.
> NXPY-80: Stick with pytest < 4

- CHANGELOG.rst
- nuxeo/models.py
- nuxeo/uploads.py
- tests/test_batchupload.py
- tests/test_document.py
Requests hangs indefinitely when the `data` of a `POST` request is a file descriptor to an empty file. This fix prevents this case from happening.
> NXPY-90: Do not open file descriptor on empty file

- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/exceptions.py
- nuxeo/utils.py
- tests/test_nuxeo.py
- tox.ini
* Added `Forbidden` exception;
* Introduced `HTTP_ERROR` in `nuxeo/client.py` to ease future addition and error handling;
* Let the possibility to pass arguments to `pytest` (eg `TOXENV=py37 tox -- -k test_upload_retry`);
* NXPY-106: Lower logging level in `get_digester()`.
> NXPY-105: Make a diffrence between HTTP 401 and 403 errors

- CHANGELOG.rst
- README.rst
- nuxeo/__init__.py
- nuxeo/constants.py
- nuxeo/uploads.py
- setup.cfg
- tests/test_batchupload.py
Also:
- Use KiB and MiB rather than Kio and Mio.
- Fix `Blob.uploadType` never set.
> NXPY-112: Update uploadedSize on each and every upload iteration

- .pre-commit-config.yaml
- CHANGELOG.rst
- README.rst
- nuxeo/client.py
- nuxeo/constants.py
- nuxeo/exceptions.py
- nuxeo/uploads.py
- tests/__init__.py
- tests/conftest.py
- tests/test_batchupload.py
- tests/test_nuxeo.py
Introduced several constants to allow customization:
- `MAX_RETRY` set to `5` (before it as used in upload and set to `3`).
- `RETRY_BACKOFF_FACTOR` set to `1` second.
- `RETRY_METHODS` set to `['GET', 'POST', 'PUT', 'DELETE']`.
- `RETRY_STATUS_CODES` set to `[429, 500, 503, 504]`.
And also, we have now `HTTPError` that inherits from `requests.exceptions.RetryError` and `NuxeoError`.
* NXPY-113: Use `requests.sessions.Session` rather than the deprecated `requests.session`.
* NXPY-114: Do not log the response of the CMIS endpoint (too long).
> NXPY-110: Max retries for all connections

- tests/test_nuxeo.py
Replace use of `NuxeoDrive.CreateFile` for `Document.Create`.
> NXPY-122: Fix tests using an unregistered operation

- CHANGELOG.rst
- nuxeo/operations.py
- nuxeo/uploads.py
- tests/test_batchupload.py
- tests/test_nuxeo.py
- tox.ini
Also removed Python 2.7 and 3.4 from tox envlist.
> NXPY-126: Allow several callables for transfer callbacks

- CHANGELOG.rst
- nuxeo/client.py
Tests are already skipped for Python 2 and 3.4.
> NXPY-125: Add a warning for Python 2 removal

- CHANGELOG.rst
- nuxeo/client.py
- setup.cfg
- tests/conftest.py
- tests/test_exception.py
- tests/test_log_response.py
- tests/test_utils.py
Now, no excuses: we cannot have `MemoryError` nor `OverflowError` anymore. The HTTP response
logger is safe to use.
I also added a simple module attribute `skip_logging` to define to `True` in test files where we do not need to log the current test on the server. This will prevent having to create a connection to the server for nothing.
> NXPY-131: Make the HTTP response logging safer

- CHANGELOG.rst
- nuxeo/users.py
- tests/test_users.py
To fetch current user details and validate credentials.
Note: at first I would have call the new method when initializing the client, but it would break Nuxeo
Drive when credentials are obsoletes. So there is just a new method and developers are free to call it.
> NXPY-68: Add the users.current_user() method

- .coveragerc
- CHANGELOG.rst
- README.rst
- examples/blobs.rst
- nuxeo/constants.py
- nuxeo/exceptions.py
- nuxeo/handlers/__init__.py
- nuxeo/handlers/default.py
- nuxeo/handlers/s3.py
- nuxeo/models.py
- nuxeo/uploads.py
- nuxeo/utils.py
- setup.cfg
- tests/server.py
- tests/test_batchupload.py
- tests/test_setup.py
- tests/test_upload_s3.py
- tests/test_utils.py
- tox.ini
I split the upload mecanism into several parts:
- the default upload provider in `handlers/default.py`
- the Amazon S3 upload provider in `handlers/s3.py`
By default, the default provider is used, so there is no behavior change. If one wants to use S3, just pass `"handler="s3"` to `nuxeo.uploads.batch()`.
When using S3, to allow to resume a paused/failed upload, AWS credentials and the mutlipart upload ID are needed. So the uploader will call all callbacks *before* starting the upload. That way, one will be able to save those details for later use.
When I tested, I saved the `ChunkUploaderS3` object using pickle. This may be a way to save things for ones in need of inspiration.
Unortunately, no integration tests were added because there is no available server configured
with S3 on our …
> NXPY-138: Add the Amazon S3 provider for uploads

- CHANGELOG.rst
- nuxeo/handlers/s3.py
- nuxeo/models.py
- tests/test_upload_s3.py
Also aligned `ChunkUploaderS3.iter_upload()` on its own docstring: it now yields itself before starting uploading contents.
Before the patch, callbacks were called and this was really not helpful nor practical from outside the client.
> NXPY-149: Add Batch.is_s3() helper

- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/comments.py
- nuxeo/documents.py
- nuxeo/groups.py
- tests/conftest.py
- tests/test_nuxeo.py
We don't want to use dots nor underscores in headers
sent to Nuxeo as NGINX doesn't allow their usage
for HTTP.
Underscores and dots have been replaced with hyphen to
not have the issue with NGINX users.
A warning is now thrown in case a dot or an underscore
is encountered in a header or a request params.
Tests will now fail if a warning is encountered.
Also changelog has been updated.
> NXPY-155: Don't use dots or underscores in custom HTTP headers

- nuxeo/auth.py
- nuxeo/client.py
- nuxeo/comments.py
- nuxeo/compat.py
- nuxeo/directories.py
- nuxeo/documents.py
- nuxeo/endpoint.py
- nuxeo/exceptions.py
- nuxeo/groups.py
- nuxeo/handlers/default.py
- nuxeo/handlers/s3.py
- nuxeo/models.py
- nuxeo/operations.py
- nuxeo/tasks.py
- nuxeo/uploads.py
- nuxeo/users.py
- nuxeo/utils.py
- nuxeo/workflows.py
Allow outdated servers (without the `refreshToken` API) to still work with S3.
It will just end on a ExpiredToken error, but it is better than a 404 error.
> NXPY-163: Still allow outdated servers to use the S3 batch handler

- .github/workflows/lint.yml
- .github/workflows/types.yml
- .github/workflows/unit_tests.yml
- CHANGELOG.rst
- README.rst
- setup.cfg
- tests/test_repository.py
- tox.ini
Dropped the support for Python 3.4 at the same time.
> NXPY-166: Move to GitHub Actions for testing

- CHANGELOG.rst
- nuxeo/constants.py
- `TIMEOUT_CONNECT`: 5 -> 10
- `TIMEOUT_READ`: 30 -> 600
It happens that the `TIMEOUT_READ` is set at the socket level at the first HTTP(S) connection. And then this value is used for next calls. And even if we set a higher value in specific calls, it will not be taken into account. So we are now using a bigger value to prevent `socket.timeout: The write operation timed out` errors at the SSL level.
> NXPY-171: Set higher default timeouts

- nuxeo/handlers/s3.py
It happens that `access_key` and `secret_key` were inverted. Bad names ...
> NXPY-163: Fix AuthorizationHeaderMalformed

- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/handlers/s3.py
- nuxeo/models.py
- nuxeo/uploads.py
- tests/test_upload_s3.py
Before the patch, the key was computed using the blob name.
And it would fail if the name contains disallowed characters like parenthesis:
HTTPError(400), error: 'java.lang.IllegalArgumentException: Invalid key: file (1).bin'
So the new code now uses a UUID.
> NXPY-178: Use a uniq ID for the S3 direct upload key

- .pre-commit-config.yaml
- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/constants.py
- nuxeo/tcp/__init__.py
- nuxeo/tcp/tcp_keep_alive_probes.py
- setup.cfg
The patch was highly inspired by finbourne/lusid-sdk-python#58.
> NXPY-182: Set the TCP keep alive option by default

- CHANGELOG.rst
- nuxeo/handlers/default.py
- nuxeo/models.py
- nuxeo/operations.py
- nuxeo/uploads.py
The `Blob.batch_id` attribute is now deprecated and will be removed in version 4.0.
> NXPY-185: Add the Blob.batchId attribute

- CHANGELOG.rst
- nuxeo/handlers/s3.py
This will fix document preview on Web-UI when updating a blob with the S3 upload provider.
Also fix a flake8 error:
C414 Unnecessary list call within sorted().
> NXPY-188: Set the Content-Type for uploads done via S3

- .github/workflows/unit_tests.yml
- CHANGELOG.rst
- setup.cfg
- tests/test_batchupload.py
- tox.ini
Also test only only Nuxeo 10.10 and lower + upper Python supported versions.
> NXPY-192: Add support for Python 3.10

- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/constants.py
- nuxeo/exceptions.py
- tests/test_batchupload.py
- tests/test_exception.py
Introduced:
- `OngoingRequestError` and `Conflict` exceptions.
- `IDEMPOTENCY_KEY` constant.
> NXPY-199: Add support for idempotent calls

- CHANGELOG.rst
- examples/blobs.rst
- nuxeo/handlers/s3.py
- tests/test_batchupload.py
- tests/test_upload_s3.py
The PR simply moves credential renewals to `ChunkUploaderS3` as it is useless to use that mechanism for non-chunked uploads.
> NXPY-205: Improve S3 non-chunked uploads

- examples/authentication.rst
- nuxeo/auth/oauth2.py
Allowing null endpoints will ease the Nuxeo Drive implementation
Default values are stored into constants and could be changed by implementations.
> NXPY-201: Allow null endpoints

- examples/authentication.rst
- nuxeo/auth/oauth2.py
- nuxeo/exceptions.py
- tests/test_exception.py
Also simplified the `OAuth2Error` exception as the stacktrace was not useful.
> NXPY-201: Allow more extensability of request_token()

- CHANGELOG.rst
- nuxeo/auth/oauth2.py
- nuxeo/client.py
- nuxeo/utils.py
- tests/test_log_response.py
It is necessary to be able to log requests from the OAuthLib.
> NXPY-201: Move NuxeoClient._log_response() to utils.py::log_reponse()

- CHANGELOG.rst
- nuxeo/auth/oauth2.py
- setup.cfg
Also:
- NXPY-231: Prevent warnings when packaging the module
> NXPY-230: Allow to pass requests arguments to the OAuth2 client

- CHANGELOG.rst
- nuxeo/__init__.py
- setup.cfg
NXPY-236:Release python client
> NXPY-236:Release python client

- .github/workflows/release.yml
- CHANGELOG.rst
Due to https://github.com/nuxeo/nuxeo-python-client/actions/runs/8735588141/job/23970902213 
Reverted pypa/gh-action-pypi-publish from release/v1 to master
> NXPY-256: Upgrade from node 16 to node 20
