- nuxeo/__init__.py
- nuxeo/batchupload.py
- nuxeo/repository.py
- tests/test_batchupload.py
No more double slashes in URLs.
> NXPY-22: Sanitize relative URLs

- nuxeo/batchupload.py
- nuxeo/blob.py
- nuxeo/operation.py
* Optimized RegExp in `safe_filename`
> NXPY-23: Remove obsolete compatibility code

- nuxeo/batchupload.py
- nuxeo/blob.py
- nuxeo/common.py
- nuxeo/directory.py
- nuxeo/document.py
- nuxeo/groups.py
- nuxeo/nuxeo.py
- nuxeo/operation.py
- nuxeo/repository.py
- nuxeo/users.py
- nuxeo/workflow.py
- tests/common.py
- tests/test_batchupload.py
- tests/test_directory.py
- tests/test_groups.py
- tests/test_nuxeo.py
- tests/test_operation.py
- tests/test_repository.py
- tests/test_users.py
- tests/test_workflows.py
> NXPY-24: Cleanup the whole source tree

- CHANGELOG.rst
- README.rst
- examples/blobs.rst
- examples/create_proxy.py
- examples/directories.rst
- examples/documents.rst
- examples/find_duplicates.py
- examples/helpers.rst
- examples/requests.rst
- examples/snippets.rst
- examples/users_and_groups.rst
- nuxeo/nuxeo.py
Remove examples from the README.rst and put them in new .rst and .py files in the examples/ folder.
> NXPY-11: Add examples

- CHANGELOG.rst
- examples/snippets.rst
- nuxeo/batchupload.py
- nuxeo/blob.py
- nuxeo/common.py
- nuxeo/exceptions.py
- nuxeo/nuxeo.py
- nuxeo/repository.py
- setup.cfg
- tests/conftest.py
- tests/test_batchupload.py
- tests/test_document.py
- tests/test_nuxeo.py
- tests/test_operation.py
- tests/test_repository.py
- tests/test_workflows.py
Remove urllib2 and poster, add requests and logging
> NXPY-16: Make HTTP requests with Requests library

- CHANGELOG.rst
- nuxeo/blob.py
- nuxeo/common.py
- nuxeo/exceptions.py
- nuxeo/nuxeo.py
- nuxeo/repository.py
- nuxeo/workflow.py
- tests/conftest.py
- tests/test_batchupload.py
- tests/test_directory.py
- tests/test_document.py
- tests/test_groups.py
- tests/test_nuxeo.py
- tests/test_repository.py
- tests/test_users.py
- tests/test_workflows.py
> NXPY-36: Remove unused code, add tests

- CHANGELOG.rst
- nuxeo/client.py
- tests/test_nuxeo.py
Also fixed a test on Python 3.
> NXPY-55: Add server version getter API

- examples/documents.rst
- nuxeo/client.py
- nuxeo/models.py
* Documentation error
* Imports in models.py
* Log parameters in client.py
> NXPY-55: Several fixes

- CHANGELOG.rst
- README.rst
- nuxeo/constants.py
> NXPY-61: Release 2.0.0

- README.rst
A little display fix. I did not want to create a ticket just for that, so it will be part of NXPY-58 :)
> NXPY-58: Fix badges URL

- ftest/pom.xml
- tests/test_utils.py
NXPY-78: Bump the server version from 10.3 to 10.10
> NXPY-77: Extend guess_mimetype test

- nuxeo/models.py
- nuxeo/workflows.py
Also:
- Fix missing argument type annotation in `Batch.attach()`;
- Fix misplaced type annotations comment in `Group.delete()`.
> NXPY-81: Fix workflows.py:113:9: F821 undefined name 'Task'

- CHANGELOG.rst
- nuxeo/__init__.py
- nuxeo/uploads.py
- setup.cfg
- tests/test_batchupload.py
* Also bump the version to 2.0.6.
> NXPY-89: Add repr(Uploader) to ease debug

- nuxeo/models.py
- tests/conftest.py
Also, remove automatic delete of all workspaces in tests.
> NXPY-88: Handle empty BufferBlob

- setup.cfg
- tests/test_repository.py
- tox.ini
Also tell everyone we support Python 3.8.
> NXPY-93: Fix test_locking()

- CHANGELOG.rst
- README.rst
- ftest/itests.xml
- ftest/pom.xml
- ftest/src/test/resources/cors-config.xml
- nuxeo/client.py
- tests/__init__.py
- tests/test_batchupload.py
- tests/test_nuxeo.py
- tests/test_utils.py
- tox.ini
> NXPY-92: Fix server_info() default value check

- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/documents.py
- nuxeo/uploads.py
- tests/test_nuxeo.py
- tests/test_repository.py
* Fixed a memory leak and reference cycle in `NuxeoClient.request()`;
* Simplyfied and fixed a reference cycle in uploads.py::`API.send_data()`;
* Fixed a small typo in documents.py::`API.convert()`;
* Reviewed `test_fetch_acls()` to pass with local server;
* Reviewed `test_server_info()` and use a bad domain name
that does not exist to have a smaller timeout.
> NXPY-100: Improve memory consumption

- nuxeo/client.py
* Make `Client._log_response()` a static method;
* Restore the old behavior when logging big response contents;
* Use `response.cookies` rather than ones from the global session;
* Add comment about why not use response.text;
* Use single quotes everywhere.
And we are now back to 100% coverage.
> NXPY-100: Improvements

- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/constants.py
Introduced 2 constants: `TIMEOUT_CONNECT` and `TIMEOUT_READ`.
> NYPY-111: Add timeouts handling

- .coveragerc
- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/exceptions.py
- nuxeo/operations.py
- tests/test_exception.py
- tests/test_nuxeo.py
- tests/test_repository.py
Also:
- NXPY-119: Remove the requests warning.
- NXPY-120: Add a test for unavailable converters.
> NXPY-118: Missing status code from Forbidden and Unauthorized exceptions

- nuxeo/client.py
- nuxeo/documents.py
- tests/test_repository.py
> NXPY-137: Use of the UnavailableConvertor exception instead

- CHANGELOG.rst
- examples/comments.rst
- examples/documents.rst
- nuxeo/__init__.py
- nuxeo/client.py
- nuxeo/comments.py
- nuxeo/documents.py
- nuxeo/models.py
- tests/test_comments.py
Note that entities are not yet handled.
> NXPY-141: Add the Comments API

- examples/comments.rst
- examples/snippets.rst
- nuxeo/comments.py
- nuxeo/documents.py
- nuxeo/models.py
- tests/test_comments.py
- tests/test_document.py
- Added helpers for comment replies.
- Simplified comments.py::`API.get()` arguments.
- Reworked comments tests.
> NXPY-141: Comments API clean-up and improvements

- CHANGELOG.rst
- nuxeo/models.py
- tests/test_repository.py
Also sorted all `._valid_properties`.
> NXPY-143: Remove duplicate constructors code in models.py

- nuxeo/handlers/s3.py
- Minimum `MaxParts` value is 0 (`ListParts` API).
- Reduce side effects of `ChunkUploaderS3._state()`.
- Also handle the case when an given multipart upload ID exists but without uploaded parts yet. Before the patch, a new MPU was initiated, now the MPU is resumed.
Note: tests pass with a unmerged patch for moto (NXPY-147).
> NXPY-138: S3 adjustements

- CHANGELOG.rst
- nuxeo/handlers/default.py
- nuxeo/handlers/s3.py
- nuxeo/utils.py
- tests/test_utils.py
- NXPY-152: Remove Uploader assert statements
> NXPY-151: Do not log the full exception when retrieving MPU parts

- CHANGELOG.rst
- nuxeo/handlers/s3.py
- tests/test_upload_s3.py
[View issue in JIRA](https://jira.nuxeo.com/browse/NXPY-154)
> NXPY-154: Fix S3 client instanciation not thread-safe

- nuxeo/handlers/s3.py
- tests/test_upload_s3.py
Also fixed the case when `entrypoint` is empty.
> NXPY-158: Handle the new path-style option

- .github/workflows/unit_tests.yml
https://doc.nuxeo.com/nxdoc/monitoring-and-maintenance/#nuxeo-server-running-and-components-loading-statuses
> NXPY-166: Update the URL used to check if the server is up

- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/constants.py
- nuxeo/tcp/__init__.py
- nuxeo/tcp/tcp_keep_alive_probes.py
Also fixed Python 2.7 support.
> NXPY-183: Refactored the TCP keep-alive code

- nuxeo/handlers/s3.py
- tests/test_auth.py
Also:
-  NXPY-205: Clean-up imports
> NXPY-203: Fix test_portal_sso_digest_algorithm_not_found() on Python 2.7

- CHANGELOG.rst
- nuxeo/client.py
- tests/test_log_response.py
Co-authored-by: Romain Grasland <rgrasland@nuxeo.com>
> NXPY-213: Handle incomplete serialized HTTP error

- CHANGELOG.rst
- examples/find_duplicates.py
- nuxeo/auth/basic.py
- nuxeo/auth/jwt.py
- nuxeo/auth/oauth2.py
- nuxeo/auth/portal_sso.py
- nuxeo/auth/token.py
- nuxeo/auth/utils.py
- nuxeo/handlers/default.py
- nuxeo/utils.py
- tests/server.py
- tests/test_batchupload.py
- tests/test_document.py
- tests/test_nuxeo.py
- tests/test_repository.py
Removed `get_bytes()` and `get_text()` helpers.
> NXPY-129: Finish clean-up

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/types.yml
- .github/workflows/unit_tests.yml
- CHANGELOG.rst
> NXPY-228: Use proper job names in GitHub workflows

- CHANGELOG.rst
- nuxeo/models.py
- nuxeo/uploads.py
- tests/test_model.py
Co-authored-by: Romain Grasland <rgrasland@nuxeo.com>
> NXPY-232: Allow specifying the upload provider type in the batch details

- .pre-commit-config.yaml
- CHANGELOG.rst
> NXPY-237: Update Dependencies

- CHANGELOG.rst
- nuxeo/client.py
- nuxeo/documents.py
- nuxeo/exceptions.py
- nuxeo/models.py
- nuxeo/utils.py
- tests/conftest.py
- tests/constants.py
- tests/manual/many_small_files.py
- tests/manual/one_big_file.py
- tests/test_batchupload.py
- tests/test_log_response.py
- tests/test_repository.py
- tests/test_upload_s3.py
NXPY-239: Fix tests cases on Python
> NXPY-239: Fix tests cases on Python

- CHANGELOG.rst
- nuxeo/auth/token.py
- nuxeo/client.py
- nuxeo/comments.py
- nuxeo/documents.py
- nuxeo/endpoint.py
- nuxeo/groups.py
- nuxeo/handlers/s3.py
- nuxeo/models.py
- nuxeo/operations.py
- nuxeo/uploads.py
- nuxeo/users.py
- nuxeo/utils.py
- tests/conftest.py
- tests/constants.py
- tests/test_batchupload.py
- tests/test_comments.py
- tests/test_document.py
- tests/test_groups.py
- tests/test_nuxeo.py
- tests/test_repository.py
- tests/test_upload_s3.py
- tests/test_users.py
- tests/test_workflows.py
NXPY-238: Fix issue with Self signed certificates
> NXPY-238: Fix issue with Self signed certificates

- CHANGELOG.rst
NXPY-250: Release python client 6.1.1
> NXPY-250: Release python client 6.1.1

- CHANGELOG.rst
- nuxeo/client.py
- tests/unit/test_client.py
NXPY-258: File download from aws S3 with auto-redirect not working in case of OAuth
> NXPY-258: File download from aws S3 with auto-redirect not working in case of OAuth

- CHANGELOG.rst
> NXPY-257: Release 6.1.2

- CHANGELOG.rst
NXPY-257:Release python client 6.1.2
>  NXPY-257:Release python client 6.1.2
